# =================================================
# Configuración para text_extractor.py
# =================================================

github:
  repos:
    - owner: Gym
      repo: blog
      path: /

  